### ISSUE TITLE
Question on user_repository.go

### ISSUE THREAD

**Issue by alochym01** [victorsteven/food-app-server#1]
Hi just read your post on DDD and it is very interesting 
for a bit clean on persistence/user_repository.go

Could i change 
```go
func NewUserRepository(db *gorm.DB) *UserRepo {
	return &UserRepo{db}
}
//UserRepo implements the repository.UserRepository interface
var _ repository.UserRepository = &UserRepo{}
```

to 
```go
func NewUserRepository(db *gorm.DB) repository.UserRepository {
	return &UserRepo{db}
}
```

so i could remove a statement  "var _ repository.UserRepository = &UserRepo{}"

let me know your thought

thank you

**Comment by victorsteven** [comment]
Hi, thanks for reading. It is not always advisable to return an interface.

If a struct can be returned instead of an interface, then return the struct.
